---
- name: Start redmine container
  community.docker.docker_container:
    name: myapplication
    image: "redmine:{{ redmine_version }}"
    state: started
    container_default_behavior: no_defaults
    ports:
      - "{{ redmine_port }}:3000"
    env:
      REDMINE_DB_POSTGRES: "{{ redmine_db_postgres }}"
      REDMINE_DB_PORT: "{{ redmine_db_port }}"
      REDMINE_DB_DATABASE: "{{ redmine_db_database }}"
      REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
      REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
